.PHONY: install run build test cli

dev:
	npm run dev

install:
	npm install

run:
	npm start

build:
	export BASE_URL=https://lowess.github.io/110lab
	npm run build

test:
	npm run test

cli:
	node ./tools/cli/cli.js
